# Generated by Django 3.2.23 on 2023-12-07 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20231207_1219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='on_time_delivery_date',
            new_name='on_time_delivery_rate',
        ),
        migrations.CreateModel(
            name='HistoricalPerfromance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('on_time_delivery_rate', models.FloatField()),
                ('quality_rating_avg', models.FloatField(default=0.0)),
                ('average_response_time', models.FloatField()),
                ('fulfillment_rate', models.FloatField()),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.vendor')),
            ],
        ),
    ]
