# Generated by Django 5.0 on 2023-12-24 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_historicalperformance_average_response_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='quality',
            new_name='quantity',
        ),
    ]
