# Generated by Django 5.0 on 2024-01-19 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_quality_purchaseorder_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalperformance',
            old_name='fulfillment_rate',
            new_name='fulfilment_rate',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='fulfillment_rate',
            new_name='fulfilment_rate',
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='api.vendor'),
        ),
    ]
